name: Future Peptides™
favicon: null
layout_spectrum: 0.9218335766345263
typography_spectrum: 0.8136077316012233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c150e'
    - '#4ea2c5'
    - '#8b7b65'
    - '#bead92'
  brandStrength: 0.4375
  lightness: 0.44466279190964997
  saturation: 0.1875
  rhythmicContrast: 0.10927322250790894
purpose: []
