name: Future Peptides™
favicon: null
layout_spectrum: 0.9218335766345263
typography_spectrum: 0.8136077316012233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4369615132454783
  lightness: 0.44466279190964997
  saturation: 0.2746031123679131
  rhythmicContrast: 0.10927322250790894
purpose: []
