name: Future Peptides™
favicon: null
layout_spectrum: 0.9382979
typography_spectrum: 0.8136077316012233
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Create Your Dream With Future Peptides™
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c150e'
    - '#4ea2c5'
    - '#8b7b65'
    - '#bead92'
  brandStrength: 0.4375
  lightness: 0.44466279190965
  saturation: 0.1875
  rhythmicContrast: 0.1092732225079089
purpose: []
